"""Recognize installed Hermes roots without executing process-supplied Python.

This is discovery, NOT attestation. Kernel identity, source/enrollment freshness
and exact-process authenticated completion remain mandatory in serving_admission.
Only whole, known launcher ASTs are accepted; substring hits in helper arguments
or arbitrary Python wrappers are not runtime roots.
"""
from __future__ import annotations

import ast
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MODULES = {'hermes_cli.main': 'hermes', 'run_agent': 'run_agent.py'}
MAX_SOURCE = 65536


def _tree(source):
    if len(source) > MAX_SOURCE:
        return None
    try:
        return ast.parse(source)
    except (SyntaxError, ValueError, RecursionError):
        return None


def _same(tree, source):
    expected = _tree(source)
    try:
        return expected is not None and ast.dump(tree) == ast.dump(expected)
    except RecursionError:
        return False


def _module_args(module, args):
    return [MODULES[module], *args] if module in MODULES else None


def _inline(source, args):
    tree = _tree(source)
    if tree is None:
        return None
    # Compare the complete AST against code generated by trusted installed
    # launcher functions. Never import, eval, exec or run process-supplied code.
    from hermes_cli._launchers import _launcher_script, runtime_command
    if _same(tree, _launcher_script('hermes', ROOT, None)):
        if args[:1] == ['--print-runtime-command']:
            return None
        if args[:1] == ['--run-module']:
            return _module_args(args[1], args[2:]) if len(args) > 1 else None
        return ['hermes', *args]
    for module in MODULES:
        template = runtime_command(ROOT, module=module, python='/python')[3]
        if _same(tree, template):
            return _module_args(module, args)
    # venv_sync.relaunch_command captures sys.argv as a literal list. Inspect
    # only string constants, then match the entire four-statement wrapper.
    if len(tree.body) != 4 or args:
        return None
    assignment = tree.body[2]
    if not isinstance(assignment, ast.Assign) or not isinstance(assignment.value, ast.List):
        return None
    elements = assignment.value.elts
    if not elements or any(not isinstance(e, ast.Constant) or type(e.value) is not str for e in elements):
        return None
    captured = [e.value for e in elements]
    prefix = f'import sys, runpy; sys.path.insert(0, {str(ROOT)!r}); sys.argv = {captured!r}; '
    for module in MODULES:
        if _same(tree, prefix + f"runpy.run_module({module!r}, run_name='__main__', alter_sys=True)"):
            return _module_args(module, captured[1:])
    for path, name in ((ROOT / 'run_agent.py', 'run_agent.py'),
                       (ROOT / 'hermes_cli/main.py', 'hermes'),
                       (ROOT / 'venv/bin/hermes', 'hermes')):
        if captured[0] == str(path) and _same(tree, prefix + f"runpy.run_path({str(path)!r}, run_name='__main__')"):
            return [name, *captured[1:]]
    return None


def runtime_argv(argv):
    """Return application argv for a recognized root, otherwise None.

    Parse interpreter options only before its entrypoint. In particular -m
    used by Python must never be mistaken for Hermes's model option.
    """
    if not argv or any(not isinstance(a, str) for a in argv):
        return None
    executable = Path(argv[0]).name
    if executable == 'hermes':
        if argv[1:2] == ['--run-module']:
            return _module_args(argv[2], argv[3:]) if len(argv) > 2 else None
        if argv[1:2] == ['--print-runtime-command']:
            return None
        return ['hermes', *argv[1:]]
    if not re.fullmatch(r'python(?:\d+(?:\.\d+)*)?', executable):
        return None
    i = 1
    isolated = False
    while i < len(argv):
        word = argv[i]
        if word in ('-I', '-B', '-E', '-s', '-S', '-u', '-O', '-OO'):
            isolated |= word == '-I'
            i += 1
        elif word in ('-W', '-X') and i + 1 < len(argv):
            i += 2
        elif word.startswith(('-W', '-X')) and len(word) > 2:
            i += 1
        else:
            break
    if i >= len(argv):
        return None
    if argv[i] == '-c':
        return _inline(argv[i + 1], argv[i + 2:]) if isolated and i + 1 < len(argv) else None
    if argv[i] == '-m':
        return _module_args(argv[i + 1], argv[i + 2:]) if i + 1 < len(argv) else None
    entry = argv[i]
    if entry in ('run_agent.py', str(ROOT / 'run_agent.py')):
        return ['run_agent.py', *argv[i + 1:]]
    if entry in ('hermes', str(ROOT / 'hermes_cli/main.py'), str(ROOT / 'venv/bin/hermes')):
        return ['hermes', *argv[i + 1:]]
    return None


def runtime_kind(argv):
    args = runtime_argv(argv)
    if args is None:
        return None
    # Conservative: a gateway/dashboard token can never become an executor,
    # even if ambiguously supplied as another option's value.
    if 'gateway' in args[1:]:
        return 'gateway'
    if 'dashboard' in args[1:]:
        return 'dashboard'
    if 'relay' in args[1:]:
        return 'relay'
    return 'cli'
